const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';

const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';

const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

module.exports = {
  FETCH_TASKS_REQUEST,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAILURE
};
